### ISSUE TITLE
How do you schedule ?

### ISSUE THREAD

**Issue by marc-cizeron** [vincentwolsink/home_assistant_micronova_agua_iot#41]
Hi,

I wonder how do you schedule the heating with your stove and home hassistant ?

Before the [v0.2.0-beta6](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.2.0-beta6) version, Here's how I do it:

First, i extract the swith to on/off the stove :
```
- platform: template
  switches:
    stove_heater:
      value_template: "{{ is_state('climate.poele', 'heat') }}"
      turn_on:
        service: climate.turn_on
        target:
          entity_id: climate.poele
      turn_off:
        service: climate.turn_off
        target:
          entity_id: climate.poele
```

Then, with the switche i use the Home Assistant's Generic Thermostat (https://www.home-assistant.io/integrations/generic_thermostat/) :
```
- platform: generic_thermostat
  name: JM Poêl
  heater: switch.stove_heater
  #  target_sensor: sensor.ts0201_i_temperature
  target_sensor: sensor.temperature_moyenne
  ac_mode: false
  min_temp: 15
  max_temp: 26
  cold_tolerance: 0.5
  hot_tolerance: 1
  precision: 0.1
  min_cycle_duration:
    minutes: 10
  home_temp: 20.0
  sleep_temp: 17.0
  activity_temp: 19.0
  comfort_temp: 21.0
  away_temp: 17.0
  target_temp_step: 0.5
  initial_hvac_mode: heat
```

And finally I use the Scheduler integration for HA (https://community.home-assistant.io/t/scheduler-card-custom-component/217458) to make schedule. For exemple on monday morning set the temperature to 21°C at 6 am.

I try to use disable the generic climate and use the one from the integration and enable the standby mode, but It seems that this mode only stops the stove. So if at 6 am the temp >= 21°C, the stove is startup because of the scedule. It wasn't the case with the generic thermostat.

My question is : How do you manage the planning? Is there any misunderstanding from me?
