### ISSUE TITLE
no more status codes

### ISSUE THREAD

**Issue by silkyclouds** [vincentwolsink/home_assistant_micronova_agua_iot#49]
Hi there, 

Last year I created a set of notifications based on the status codes of my stove, like that one :

````
alias: "Notification : plus de pellets insert"
description: ""
trigger:
  - platform: state
    entity_id: sensor.device_status
    to: "12"
action:
  - service: notify.alexa_media_echo_salle_a_manger
    data:
      message: Il n'y a plus de pellets dans l'insert, veuillez en rajouter
  - service: notify.groupe_de_notifications_famille
    data:
      message: "J'ai FAIM !!! donnez-moi du pellet a manger humains ! "
      title: Insert Montefiore
mode: single
````
I noticed these notifications are not working anymore, and it seems your integration totally removed the status codes reported by the stoves. 

![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/23377067/aeae3c2e-8e81-4167-beea-f9d698c9b98e)

Would it be possible to get these back in order to allow people to keep triggering notifications when a stove enters a specific mode (above, an example of a notification I was getting when the stove was empty (no more pellet). 

Thanks !
